language: node_js

node_js:
  - 6
  - 7
  - 8

install:
  - yarn

cache:
  yarn: true
  directories:
  - node_modules

script:
  - yarn build

deploy:
  provider: npm
  email: "hello@gorillab.co"
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
    node: '8'
  tag: next

notifications:
  email: false
  slack:
    secure: NTYVzVDEICJ0Dd6PH1BVXwtmxLQhG0mC0sfWmqCUfsMSEjLz23G9xHXp2M1pipvdH2gn5y3FM7P04XImgfPAUuDOC9rsyv0oPWbY8X0jaKhLihgFZtitKmwAxWpRfpeSYMqeYdVFcWC/T7LMZ71LlnV9/ys+OgEw7/iankdX8QAF48IijHTiogpK284B0LbNSBHWtuxO+ryi4LjgwxlPISc1fSdvzyefPuxe1zg3BKF86ei7hnb8NPZG1qPLLwnbNmBOsxVGuZ4EUTQxOfSCYkGclfSomUxAv0cB40Qtvu2ehSe54RGbeA6j01349DkcES1AlpS4cnU3dzIi8gqop5rb1WQXL/2vn2XflUsV/ZMXXHu9jBPzUqhJgYpu4vhI5P792UIVA1hEDsXOjgmIyw+wFBny9GmvlHiAwEPxOsbHUXxC9mAmyYhGj03qsqRMip5H68KFeo+GpP1ElytSFHi1yFiZncbuTe6yOIDf9DbzrX9qra/DrQBM52Mm9PQEjQPji+uz7CHVwGmHdz53kB9qUj6N6LBPEDXVFiYW/Vav3zHlZWAXdYnzzpuQp0KpbMmb0D55KQdy3V/mXZaLiSxVQLhDiz6l/7ApGj/o+mpyBhagBkuc1kyhkrRDKxMpNUFax3iHofPC3YPyOpksCKT9LlSRCb/7AXqYrzZU2xg=
